[package]
name = "namada_test_utils"
description = "Namada test utilities"
resolver = "2"
authors.workspace = true
edition.workspace = true
documentation.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
namada_core.workspace = true
namada_state.workspace = true

borsh.workspace = true
prost.workspace = true
strum.workspace = true
