merge_queue:
  max_parallel_checks: 3

queue_rules:
  - name: main-queue
    batch_size: 3
    queue_conditions:
      - "#approved-reviews-by >= 1"
      - base = main
    merge_method: merge
    autosquash: true   

  - name: backport-apps-101.1-queue
    batch_size: 3
    queue_conditions:
      - "#approved-reviews-by >= 1"
      - base = maint-101.1
    merge_method: merge
    autosquash: true   

  - name: backport-libs-0.150-queue
    batch_size: 3
    queue_conditions:
      - "#approved-reviews-by >= 1"
      - base = maint-libs-0.150
    merge_method: merge
    autosquash: true   

pull_request_rules:
  - name: automatic merge to main or backport branch
    conditions:
      - label = "merge"
      - label != "do-not-merge"
      - "#approved-reviews-by >= 1"
      - or:
        - base = main
        - base = maint-101.1
        - base = maint-libs-0.150
    actions:
      queue:

  - name: notify when a PR is removed from the queue
    conditions:
      - queue-dequeue-reason != none
      - queue-dequeue-reason != pr-merged
    actions:
      comment:
        message: >
          Hey @{{author}}, your pull request has been dequeued due to the following
          reason: {{queue_dequeue_reason}}.

          Sorry about that, but you can requeue the PR by using `@mergifyio requeue`
          if you think this was a mistake.

  - name: backport PR to apps 101.1 lane
    conditions:
      - label = backport-101.1
    actions:
      backport:
        branches:
          - "maint-101.1"

  - name: backport PR to libs 0.150 lane
    conditions:
      - label = backport-libs-0.150
    actions:
      backport:
        branches:
          - "maint-libs-0.150"
