merge_queue:
  max_parallel_checks: 3

queue_rules:
  - name: duplicated main-queue from automatic merge to main or backport branch
    batch_size: 3
    queue_conditions:
      - "#approved-reviews-by >= 1"
      - base = main
      - label = "merge"
      - label != "do-not-merge"
      - "#approved-reviews-by >= 1"
      - &id001
        or:
          - base = main
          - base = maint-0.45
    merge_conditions: []
    merge_method: merge
    autosquash: true
  - name: main-queue
    batch_size: 3
    queue_conditions:
      - "#approved-reviews-by >= 1"
      - base = main
    merge_method: merge

  - name: duplicated backport-0.45-queue from automatic merge to main or backport
      branch
    batch_size: 3
    queue_conditions:
      - "#approved-reviews-by >= 1"
      - base = maint-0.45
      - label = "merge"
      - label != "do-not-merge"
      - "#approved-reviews-by >= 1"
      - *id001
    merge_conditions: []
    merge_method: merge
    autosquash: true
  - name: backport-0.45-queue
    batch_size: 3
    queue_conditions:
      - "#approved-reviews-by >= 1"
      - base = maint-0.45
    merge_method: merge


pull_request_rules:
  - name: notify when a PR is removed from the queue
    conditions:
      - queue-dequeue-reason != none
      - queue-dequeue-reason != pr-merged
    actions:
      comment:
        message: >
          Hey @{{author}}, your pull request has been dequeued due to the following
          reason: {{queue_dequeue_reason}}.

          Sorry about that, but you can requeue the PR by using `@mergifyio requeue`
          if you think this was a mistake.

  - name: backport PR to 0.45 lane
    conditions:
      - label = backport-45
    actions:
      backport:
        branches:
          - "maint-0.45"
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
