merge_queue:
  max_parallel_checks: 3

queue_rules:
  - name: main-queue
    batch_size: 3
    queue_conditions:
      - "#approved-reviews-by >= 1"
      - base = main
    merge_method: rebase
    update_method: rebase
    autosquash: true # requires `update_method: rebase`

  - name: backport-apps-1.1-queue
    batch_size: 3
    queue_conditions:
      - "#approved-reviews-by >= 1"
      - base = maint-1.1
    merge_method: rebase
    update_method: rebase
    autosquash: true # requires `update_method: rebase`

  - name: backport-libs-0.47-queue
    batch_size: 3
    queue_conditions:
      - "#approved-reviews-by >= 1"
<<<<<<< HEAD
      - base = maint-libs-0.47
    merge_method: merge
    autosquash: true   
=======
      - base = maint-libs-0.48
    merge_method: rebase
    update_method: rebase
    autosquash: true # requires `update_method: rebase`
>>>>>>> 6154e11d6 (mergify: merge and update with rebase to allow auto-squash)

pull_request_rules:
  - name: automatic merge to main or backport branch
    conditions:
      - label = "merge"
      - label != "do-not-merge"
      - "#approved-reviews-by >= 1"
      - or:
        - base = main
        - base = maint-1.1
        - base = maint-libs-0.47
    actions:
      queue:

  - name: notify when a PR is removed from the queue
    conditions:
      - queue-dequeue-reason != none
      - queue-dequeue-reason != pr-merged
    actions:
      comment:
        message: >
          Hey @{{author}}, your pull request has been dequeued due to the following
          reason: {{queue_dequeue_reason}}.

          Sorry about that, but you can requeue the PR by using `@mergifyio requeue`
          if you think this was a mistake.

  - name: backport PR to apps 1.1 lane
    conditions:
      - label = backport-1.1
    actions:
      backport:
        branches:
          - "maint-1.1"

  - name: backport PR to libs 0.47 lane
    conditions:
      - label = backport-libs-0.47
    actions:
      backport:
        branches:
          - "maint-libs-0.47"
