merge_queue:
  max_parallel_checks: 3

queue_rules:
  - name: main-queue
    batch_size: 3
    queue_conditions:
      - "#approved-reviews-by >= 1"
      - base = main
    merge_method: merge

  - name: backport-0.46-queue
    batch_size: 3
    queue_conditions:
      - "#approved-reviews-by >= 1"
      - base = maint-0.46
    merge_method: merge

pull_request_rules:
  - name: automatic merge to main or backport branch
    conditions:
        - label = "merge"
        - label != "do-not-merge"
        - "#approved-reviews-by >= 1"
        - or:
          - base = main
          - base = maint-0.46
    actions:
      queue:
        autosquash: true   

  - name: notify when a PR is removed from the queue
    conditions:
    - queue-dequeue-reason != none
    - queue-dequeue-reason != pr-merged
    actions:
      comment:
        message: >
          Hey @{{author}}, your pull request has been dequeued due to the following
          reason: {{queue_dequeue_reason}}.

          Sorry about that, but you can requeue the PR by using `@mergifyio requeue`
          if you think this was a mistake.

  - name: backport PR to 0.46 lane
    conditions:
      - label = backport-46
    actions:
      backport:
        branches:
          - "maint-0.46"
