[package]
name = "namada_benchmarks"
description = "Namada benchmarks"
resolver = "2"
authors.workspace = true
edition.workspace = true
documentation.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[[bench]]
name = "native_vps"
harness = false
path = "native_vps.rs"

[[bench]]
name = "process_wrapper"
harness = false
path = "process_wrapper.rs"

[[bench]]
name = "host_env"
harness = false
path = "host_env.rs"

[[bench]]
name = "wasm_opcodes"
harness = false
path = "wasm_opcodes.rs"

[features]
namada-eth-bridge = [
  "namada_apps_lib/namada-eth-bridge",
]

[dependencies]

# NOTE: this crate MUST NOT import any dependency with testing features to prevent benchmarking non-production code
[dev-dependencies]
namada_apps_lib = { path = "../apps_lib", features = ["benches"] }
namada_node = { path = "../node", features = ["benches"] }
namada_vm = { path = "../vm", features = ["wasm-runtime"] }
namada_vp = { path = "../vp" }

masp_primitives.workspace = true
masp_proofs = { workspace = true, features = ["benchmarks", "multicore"] }
borsh.workspace = true
borsh-ext.workspace = true
criterion = { version = "0.5", features = ["html_reports"] }
lazy_static.workspace= true
prost.workspace = true
rand_core.workspace = true
rand.workspace = true
tempfile.workspace = true
sha2.workspace = true
wasm-instrument.workspace = true
wasmer-compiler-singlepass.workspace = true
wasmer.workspace = true
