allow-branch               = ["main", "maint-*"]
consolidate-commits        = true
pre-release-commit-message = "Namada {{version}}"
publish                    = true
push                       = false
shared-version             = false
tag                        = false
