[package]
name = "tx_ibc"
description = "WASM transaction for an IBC transfer"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
namada_tx_prelude = { workspace = true, default-features = false, features = [] }

rlsf.workspace = true
getrandom.workspace = true

[lib]
crate-type = ["cdylib"]
